// Generated by CoffeeScript 1.10.0
(function() {
  var Message;

  module.exports = Message = (function() {
    Message.me = void 0;

    Message.type = void 0;

    Message.data = void 0;

    function Message(data1, message) {
      this.data = data1;
      this.message = message;
      this.me = this;
    }

    Message.prototype.setMessage = function(message) {
      this.message = message;
      return this.me;
    };

    Message.prototype.getMessage = function() {
      return this.message;
    };

    Message.prototype.setType = function(type) {
      this.type = type;
      return this.me;
    };

    Message.prototype.getType = function() {
      return this.type;
    };

    Message.prototype.setData = function(data) {
      this.data = data;
      return this.me;
    };

    Message.prototype.getData = function() {
      return this.data;
    };

    Message.prototype.getMessage = function() {
      return {
        message: this.message,
        data: this.data
      };
    };

    return Message;

  })();

}).call(this);
