// Generated by CoffeeScript 1.10.0
(function() {
  var Message, RuntimeMessage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Message = require('./Message');

  module.exports = RuntimeMessage = (function(superClass) {
    extend(RuntimeMessage, superClass);

    RuntimeMessage.date = void 0;

    function RuntimeMessage(message) {
      RuntimeMessage.__super__.constructor.call(this, message);
      this.date = new Date();
      this.setType('RUNTIME_MESSAGE');
    }

    RuntimeMessage.prototype.getDate = function() {
      return this.date;
    };

    RuntimeMessage.prototype.setDate = function(date) {
      this.date = date;
      return this.me;
    };

    return RuntimeMessage;

  })(Message);

}).call(this);
