// Generated by CoffeeScript 1.10.0
(function() {
  var RuntimeMessage, TaskInstanceStatusMessage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  RuntimeMessage = require('./RuntimeMessage');

  module.exports = TaskInstanceStatusMessage = (function(superClass) {
    extend(TaskInstanceStatusMessage, superClass);

    TaskInstanceStatusMessage.instances = void 0;

    function TaskInstanceStatusMessage(instances, message) {
      this.instances = instances;
      TaskInstanceStatusMessage.__super__.constructor.call(this, message);
      this.setData(this.instances);
      this.setType('TASK_INSTANCE_STATUS_MESSAGE');
    }

    return TaskInstanceStatusMessage;

  })(RuntimeMessage);

}).call(this);
