// Generated by CoffeeScript 1.10.0
(function() {
  var crypto;

  crypto = require('crypto');

  module.exports = {
    hash: function(text) {
      var salt;
      salt = "I'll make you famous!";
      if (text == null) {
        text = this.text;
      }
      return crypto.createHmac('sha256', salt).update(text).digest('hex');
    },
    compare: function(pass, hpass) {
      return this.hash(pass) === hpass;
    }
  };

}).call(this);
