// Generated by CoffeeScript 1.10.0
(function() {
  var Error, RuntimeError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Error = require('./Error');

  module.exports = RuntimeError = (function(superClass) {
    extend(RuntimeError, superClass);

    RuntimeError.date = void 0;

    RuntimeError.type = 'RUNTIME_ERROR';

    function RuntimeError(message) {
      RuntimeError.__super__.constructor.call(this, message);
      this.date = new Date();
    }

    RuntimeError.prototype.getDate = function() {
      return this.date;
    };

    RuntimeError.prototype.setDate = function(date) {
      this.date = date;
      return this.me;
    };

    return RuntimeError;

  })(Error);

}).call(this);
